"use client";
import { useEffect,useMemo,useState } from "react";
import { supabase } from "../lib/supabase";
const badgeUrl="/badges/bickri-verified-badge.svg";
const COUNTRIES=["Algérie","Angola","Bénin","Botswana","Burkina Faso","Burundi","Cap-Vert","Cameroun","République centrafricaine","Tchad","Comores","République du Congo","République démocratique du Congo","Côte d’Ivoire","Djibouti","Égypte","Guinée équatoriale","Érythrée","Eswatini","Éthiopie","Gabon","Gambie","Ghana","Guinée","Guinée-Bissau","Kenya","Lesotho","Libéria","Libye","Madagascar","Malawi","Mali","Mauritanie","Maurice","Maroc","Mozambique","Namibie","Niger","Nigéria","Rwanda","São Tomé-et-Príncipe","Sénégal","Seychelles","Sierra Leone","Somalie","Afrique du Sud","Soudan du Sud","Soudan","Tanzanie","Togo","Tunisie","Ouganda","Zambie","Zimbabwe"];
type Country={name:string;code:string;position:number;[key:string]:unknown};
function flag(c:string){return c.replace(/[A-Z]/g,l=>String.fromCodePoint(127397+l.charCodeAt(0)))}
export default function HomePage(){
 const[countries,setCountries]=useState<Country[]>(COUNTRIES.map((name,i)=>({name,code:"",position:i+1})));const[search,setSearch]=useState("");const[selected,setSelected]=useState<Country|null>(null);const[orgs,setOrgs]=useState<any[]>([]);const[ps,setPs]=useState("");
 const[form,setForm]=useState({applicant_name:"",email:"",country_code:"",website:"",social_links:"",reason:""});const[submitting,setSubmitting]=useState(false);const[message,setMessage]=useState("");
 useEffect(()=>{void(async()=>{if(!supabase)return;const c=await supabase.from("africa_countries").select("*").order("position");if(c.data?.length===54)setCountries(c.data as Country[]);const o=await supabase.from("organizations").select("id,name,country,badge_serial,verification_score").eq("status","approved").order("name").limit(100);setOrgs(o.data||[])})()},[]);
 const filtered=useMemo(()=>countries.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())||c.code.toLowerCase().includes(search.toLowerCase())),[countries,search]);const profiles=useMemo(()=>orgs.filter(o=>`${o.name} ${o.country||""}`.toLowerCase().includes(ps.toLowerCase())),[orgs,ps]);
 async function submitVerification(e:React.FormEvent){e.preventDefault();setSubmitting(true);setMessage("");if(!supabase){setMessage("Service indisponible.");setSubmitting(false);return}const r=await supabase.from("verification_requests").insert({applicant_name:form.applicant_name,email:form.email||null,country_code:form.country_code,website:form.website||null,social_links:form.social_links?{links:form.social_links.split(/[,\n]+/).map(x=>x.trim()).filter(Boolean)}:{},reason:form.reason||null,status:"pending"});if(r.error)setMessage("Impossible d’envoyer la demande : "+r.error.message);else{setMessage("Demande envoyée. Elle sera examinée avant l’attribution du badge.");setForm({applicant_name:"",email:"",country_code:"",website:"",social_links:"",reason:""})}setSubmitting(false)}
 return <main><header className="site-header"><a className="brand" href="#accueil"><img src={badgeUrl} alt=""/>Bickri <b>Verified</b></a><nav><a href="#accueil">Accueil</a><a href="#pays">54 pays</a><a href="#verification">Vérification</a><a href="#annuaire">Annuaire</a><a href="#ceo">CEO</a></nav><a className="header-button" href="#verification">Demander le badge</a></header>
 <section id="accueil" className="hero section-wrap"><div><p className="eyebrow">BICKRI VERIFIED · AFRIQUE</p><h1>Une identité.<br/><em>Une confiance.</em><br/>Pour toute l’Afrique.</h1><p>Une plateforme panafricaine pour identifier et consulter les profils vérifiés.</p><a className="primary" href="#verification">Demander une vérification →</a></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1739286547828-989197737687?auto=format&fit=crop&fm=jpg&q=90&w=1800" alt="Communauté africaine"/></div></section>
 <section id="pays" className="countries section-wrap"><div className="heading"><div><p className="eyebrow">EXPLORER L’AFRIQUE</p><h2>Les 54 pays</h2></div><p>Cliquez sur un pays pour voir toutes les informations disponibles.</p></div><div className="country-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher un pays africain…"/></div><div className="country-grid">{filtered.map(c=><button className="country-card" key={c.name} onClick={()=>setSelected(c)}><span className="flag">{c.code?flag(c.code):"🌍"}</span><span><strong>{c.name}</strong><small>{c.code||`Pays ${c.position}`}</small></span><b>→</b></button>)}</div></section>
 <section id="verification" className="directory section-wrap"><div className="heading"><div><p className="eyebrow">VÉRIFICATION PANAFRICAINE</p><h2>Demander le badge Bickri Verified</h2></div><p>La demande est examinée avant l’activation du badge public.</p></div><form onSubmit={submitVerification} style={{display:"grid",gap:14,maxWidth:760}}><input required value={form.applicant_name} onChange={e=>setForm({...form,applicant_name:e.target.value})} placeholder="Nom complet ou nom de l’organisation"/><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="E-mail"/><select required value={form.country_code} onChange={e=>setForm({...form,country_code:e.target.value})}><option value="">Choisir le pays</option>{countries.map(c=><option key={c.name} value={c.code||c.name}>{c.name}</option>)}</select><input value={form.website} onChange={e=>setForm({...form,website:e.target.value})} placeholder="Site web (facultatif)"/><textarea value={form.social_links} onChange={e=>setForm({...form,social_links:e.target.value})} placeholder="Liens sociaux publics (séparés par des virgules)" rows={3}/><textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Pourquoi souhaitez-vous être vérifié ?" rows={4}/><button className="primary" disabled={submitting}>{submitting?"Envoi…":"Envoyer la demande de vérification"}</button>{message&&<p>{message}</p>}</form><div style={{marginTop:28}}><h3>Critères de contrôle</h3><p>Identité · activité réelle · présence numérique vérifiable · pays africain sélectionné · respect des critères Bickri Verified.</p></div></section>
 <section id="annuaire" className="directory section-wrap"><div className="heading"><div><p className="eyebrow">ANNUAIRE</p><h2>Profils vérifiés</h2></div><p>Seuls les profils approuvés sont affichés.</p></div><div className="country-search"><span>⌕</span><input value={ps} onChange={e=>setPs(e.target.value)} placeholder="Rechercher un profil…"/></div><div className="profile-grid">{profiles.map(p=><article className="profile" key={p.id}><img src={badgeUrl} alt=""/><div><h3>{p.name}</h3><p>{p.country||"Afrique"}</p></div><strong>✓ Vérifié</strong></article>)}</div>{!profiles.length&&<div className="empty">Aucun profil vérifié trouvé.</div>}</section>
 <section id="ceo" className="ceo section-wrap"><div className="ceo-card"><div className="avatar">MB</div><div><p className="eyebrow">DIRECTION</p><h2>Mohamed Bickri Jr.</h2><strong>CEO — Bickri Verified</strong><p>Une vision d’identité numérique claire et accessible à toute l’Afrique.</p></div><img src={badgeUrl} alt="Badge"/></div></section><footer className="footer">© 2026 Bickri Verified · Innover et réussir.</footer>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="country-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">FICHE PAYS</p><h2>{selected.code?flag(selected.code):"🌍"} {selected.name}</h2><div className="info-grid">{Object.entries(selected).filter(([k])=>k!=="position").map(([k,v])=><div className="info-item" key={k}><small>{k.replace(/_/g," ")}</small><strong>{v===""||v==null?"À compléter":typeof v==="object"?JSON.stringify(v):String(v)}</strong></div>)}</div><button className="primary full" onClick={()=>setSelected(null)}>Fermer</button></article></div>}</main> }